### ISSUE TITLE
remove any zeros between the first letter and the number

### ISSUE THREAD

**Issue by JimTrimmer** [ucdavis-bioinformatics/NeuroMabSeq#14]
It came up in previous discussion but now seeing it on the website I thought I would address it.  A few of the mAb names contain zeros.  In this form they do not match what is in publications, on the NeuroMab or Addgene websites, etc.   This may cause confusion in the research community  Best to remove any zeros. Three examples:  change K014/16.2 to K14/16.2,  K075/41.2 to K75/41.1 and N001/12.1 to N1/12.1.   Thanks.
Jim

**Comment by samhunter** [comment]
Clara has reviewed all of the sample sheets and all of the IDs should be correct now.

**Comment by JimTrimmer** [comment]
Hi Sam,
Thanks.  I just checked the website and they are still in the incorrect form (see attached), did you mean on the website or somewhere else?
Jim
[A screenshot of a social media post  Description automatically generated]

**Comment by samhunter** [comment]
Hi Jim,

I mean correct on the web site as soon as the new data is imported. Keith is doing some re-design to handle the other changes we have discussed, but the updates should be going up sooner or later.

**Comment by keithgmitchell** [comment]
Sam just means in the files he has provided me. I am wiping the database and updating the data and the database models today so it should be done later today and available on the website.

**Comment by JimTrimmer** [comment]
﻿Got it, thanks

**Comment by keithgmitchell** [comment]
Ok all of the new data that I have has been uploaded. There are 630 unique entries. I am going to do some general database summarization on a web page to see the total number for each plate and where there seems to be 13 sequences missing. Sorry for the delay yesterday. There is a lot of new data to create more sophisticated displays with so I will need to the weekend to refine how I want to present AA and domain data that I have from Sam.

**Comment by JimTrimmer** [comment]
Thanks Keith. Perhaps it is still a work in progress, but from my end I can only see 400 entries (see attached screen grab).  The other item is that the “Mab ID” names did not get corrected in the upload (see the e-mail subject line).
[A screenshot of a social media post  Description automatically generated]

**Comment by keithgmitchell** [comment]
So as far as the 400 goes. That is just the max return for a given filter that I have set. For now I will get rid of the limit but as we approach thousands and thousands of sequences it will start to bog down the system.

**Comment by keithgmitchell** [comment]
Sam do you have any comment on the MabIDs still having the zeros at the start? Seems like a few must have been missed. I can fix them on my end that i just the way they were given to me and I thought we wanted to fix that in the submission system.

**Comment by JimTrimmer** [comment]
10-4

In that case we need to have it stated somewhere prominently the total number of sequences in the database. Perhaps both on the home page and the sequence archive page?

**Comment by JimTrimmer** [comment]
One other thing, the search function is no longer working



[A screenshot of a cell phone  Description automatically generated]

**Comment by keithgmitchell** [comment]
Good catch. Just fixed that.

**Comment by keithgmitchell** [comment]
Now a table on the main home page with some stats about number of entries. Table has no limit for the time being.

**Comment by samhunter** [comment]
It looks like the samples with incorrect names are from the R&D samples we sequenced early in the project.

The IDs I have that contain 0's from that plate include:
N015/4.1
N015/39.1
N067/15.1
K075/41.1
K014/16.2

I will change these to the following and re-process:
N15/4.1
N15/39.1
N67/15.1
K75/41.1
K14/16.2

**Comment by JimTrimmer** [comment]
Hi Sam,
I did not realize this before and I guess no one else noticed either but there are 19 names that have a “0” (zero) after the slash, these are also incorrect.

I attach a screen shot.

Jim
[A screenshot of a cell phone  Description automatically generated]

**Comment by samhunter** [comment]
Hi Jim,
Unfortunately the screenshot didn't come through. I assume you mean samples like:
K64/021.1, K64/023.1, etc?

If so, these IDs all come from the samplesheets that are submitted to the DNAtech core. I will email Clara and ask her to correct them.

**Comment by keithgmitchell** [comment]
I think this has all been handled by metadata updates etc (not seeing any 0s at this point)
